services:
  - type: web
    name: pterodactyl-panel
    env: docker
    plan: free
    region: singapore
    autoDeploy: true
    buildCommand: ""
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromService:
          name: pterodactyl-db
          type: pserv
      - key: DB_DATABASE
        value: pterodactyl
      - key: DB_USERNAME
        value: pterouser
      - key: DB_PASSWORD
        sync: false

databases:
  - name: pterodactyl-db
    plan: free
    ipAllowList: []
